
default:
	javadoc -d . -classpath ../bin/classes/:$(CLASSPATH) -sourcepath ../src \
-version -author \
-header "<b>Fun Runner App</b> for Android, by <b>Charles L. Capps</b>" \
xanthanov.droid.funrun xanthanov.droid.xantools xanthanov.droid.funrun.persist xanthanov.droid.funrun.adapters xanthanov.droid.gplace
